### ISSUE TITLE
Response format changed / broke semver

### ISSUE THREAD

**Issue by dylanpyle** [radiosilence/xr#13]
Between version 0.1.10 and 0.1.11 a breaking change seems to have occurred:

Previously a request like:

```
xr.get('/something')
```

— resolved with an object containing `{ data, response, status }`. As of 0.1.11 it appears to just resolve with `data` at the top level (parsed JSON body).

Technically 0.x releases are [fair game](http://semver.org/) for breaking changes like that, but it seems like the type of thing that might have been worth at least a minor version bump given how many people are likely using default `npm install --save` behavior that allows that to be considered compatible. Also, documentation doesn't appear to have been updated

Ideally the old behavior could be restored (I can't find an obvious way to detect response status code), if not, docs should be updated to reflect the new syntax.

**edit:** here's a reduced test case just to confirm to myself that i'm not imagining this: https://jsfiddle.net/qsu8s7bk/

**Comment by dylanpyle** [comment]
Update for future code explorers: This doesn't appear to be maintained, you should use [fetch](https://github.com/github/fetch) instead.

**Comment by radiosilence** [comment]
That's really weird, I've popped a 0.2 version up that restores the original behaviour and some other useful things.
