### ISSUE TITLE
Question: how can I abort current request?

### ISSUE THREAD

**Issue by a-wart** [radiosilence/xr#14]
I'm writing some kind of autocomplete logic, so I need to abort current request if user presses other key, or something, but I can't find any public method to abort current xhr.

**Comment by hxgdzyuyi** [comment]
@a-wart you can use your custom xhr in xr.js ？

``` javascript
var xhr = new XMLHttpRequest()
xr({
  xmlHttpRequest: xhr
, ...
})

xhr.abort() // abort current request
```

**Comment by a-wart** [comment]
to be more precise, like

``` javascript
var xhr = new XMLHttpRequest()
xr({
  xmlHttpRequest: function() {
    return xhr;
  }
, ...
})

xhr.abort()
```

because you use

``` javascript
var xhr = opts.xmlHttpRequest();
```

in your code, but it looks like solution, thank you.

**Comment by hxgdzyuyi** [comment]
:+1:

**Comment by radiosilence** [comment]
I've actually got a way of doing this in 0.2, which is kind of odd but does work:

Basically you have an option called "abort" which takes a callback, which it immediately calls with an abort function as the first argument, so you can use that to abort. It's a bit strange.

**Comment by radiosilence** [comment]
@a-wart 's solution might actually be more elegant though, I think.
