### ISSUE TITLE
Expose xhr on resolve

### ISSUE THREAD

**Issue by jordanstephens** [radiosilence/xr#17]
I need to be able to read response headers when a promise is resolved. It would be really great if you could access the `xhr` on both `resolve` _and_ `reject`.

I know it will change your API, but it would be nice to be consistent and return the same response structure in both cases. Have you thought about doing something like this:

``` javascript
xhr.addEventListener(Events.LOAD, function () {
  if (xhr.status >= 200 && xhr.status < 300) {
    // I'm omitting the bit for automatically parsing the response for the moment
    resolve(res(xhr));
  } else {
    reject(res(xhr));
  }
});
```

If you want to go this way, we will want to bring back the bit of code for automatically parsing the response. I wanted to omit it above as there are a couple of ways we could go about it. Off the top of my head, we could either leave it in the eventListener callback and pass the result as an optional `_data` arg to the `res` function. Something along these lines:

``` javascript
function res(xhr, _data) {
  return {
    status: xhr.status,
    response: _data || xhr.response,
    xhr: xhr
  };
}

function xr(args) {
  return promise(args, function (resolve, reject) {

    // omitted ...

    xhr.addEventListener(Events.LOAD, function () {
      if (xhr.status >= 200 && xhr.status < 300) {
        var _data = null;
        if (xhr.responseText) {
          _data = opts.raw === true ? xhr.responseText : opts.load(xhr.responseText);
        }
        resolve(res(xhr, _data));
      } else {
        reject(res(xhr));
      }
    });

    // omitted ...
  });
}
```

Or perhaps a better solution would be to pass the `opts` object to `res` and let `res` take care of the parsing. Something like this:

``` javascript
function res(xhr, opts) {
  opts = opts || {};

  var response = null;

  if (xhr.responseText) {
    response = opts.raw === true ? xhr.responseText : opts.load(xhr.responseText);
  }

  return {
    status: xhr.status,
    response: response,
    xhr: xhr
  };
}

function xr(args) {
  return promise(args, function (resolve, reject) {

    // omitted ...

    xhr.addEventListener(Events.LOAD, function () {
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve(res(xhr, opts));
      } else {
        reject(res(xhr));
      }
    });

    // omitted ...
  });
}
```

Let me know if you're interested in this approach, and I'll submit a PR.

Thanks!

**Comment by radiosilence** [comment]
Added to 0.2.0
