### ISSUE TITLE
Add xr to window if being used in browser with no module system

### ISSUE THREAD

**Issue by bennettgoble** [radiosilence/xr#8]
xr.js' immediately-invoked function only calls the factory if a module system is present. Could this be modified to add `xr` to the window if the library is being used in a browser without a module-loader? (When `exports`/`amd` et al. are undefined)

As xr is a minimal library it'd be great to us it as part of very lean JS applications. :sparkles:

**Comment by radiosilence** [comment]
Hmmm. So babel has the option of building with --modules ignore, and with this you can create your own custom build like: `babel --modules umd -o xr.js --loose all src/xr.js`

I'm assuming that as you're not using a package loader you're also not installing from npm?

**Comment by bennettgoble** [comment]
Closing this because yes.
